services:
  - type: web
    name: leafguard-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: FRONTEND_ORIGIN
        sync: false
      - key: MODEL_PATH
        value: plant_disease_fewshot_model.h5
